### ISSUE TITLE
Upload the patches

### ISSUE THREAD

**Issue by davidkra230** [AvoMC/wine-rblx-custom#1]
Please add the patches used in the releases to the source code so we can build `wine-tkg` ourselves while still having the best experience when running roblox.

**Comment by 32bitx64bit** [comment]
Yes! Vinegar patches are broken for me on 9.0, would love to see the patch you used uploaded to the git repo, so we can compile ourselfs.

**Comment by 32bitx64bit** [comment]
Patche looks to be here.
https://github.com/AvoMC/segregrevert
Idk if its updated to work, I'll test it out.

**Comment by AvoMC** [comment]
Re continuing this project.
